### ISSUE TITLE
Ability to change QR code size

### ISSUE THREAD

**Issue by Amichayg** [rudimuc/obsidian-qrcode#1]
Right now the QR code renders at a fixed size which sometimes overshadows the rest of the document. Would be solved with ability to modify QR code size in settings/per QR code. Thanks!

**Comment by rudimuc** [comment]
Feature was added in Version 1.0.1
You can use the new Keyword 'qrcode-complex' for the ability to use options.
```qrcode-complex
    {
        "text": "this is my data",
        "width": 400,
        "margin": 20,
        "dark": "#0FF",
        "light": "#FFF"
    }
    ```
