### ISSUE TITLE
Plugin fails to load on iOS

### ISSUE THREAD

**Issue by davidolrik** [rudimuc/obsidian-qrcode#2]
When starting Obsidian the plugin fails to load, with a very rudimentary error message: `Failed to load obsidian-qr-plugin`.

The error can also be provoked by tapping "Enable" in the plugin config.

**Comment by rudimuc** [comment]
Thank you for reporting the issue. 
I can reproduce the error. Unfortunately I have no possibility to get log files.
Do you have any clue what the problem could be?

**Comment by davidolrik** [comment]
I experienced the same on desktop with a plugin of my own where I forgot to to `npm install`, so I'm guessing it's something like that.

**Comment by davidolrik** [comment]
This plugin might help: https://github.com/KjellConnelly/obsidian-dev-tools

**Comment by AnalogCyan** [comment]
I also have this issue on Android.

I was able to inspect Obsidian on my phone from my PC over ADB and got the following error in the console:

```js
app.js:1

    Plugin failure: obsidian-qrcode-plugin ReferenceError: Buffer is not defined
    at Object.alloc (eval at <anonymous> (app.js:1), <anonymous>:199:3)
    at anonymous (eval at <anonymous> (app.js:1), <anonymous>:1025:24)
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
(anonymous) @ app.js:1
```

**Comment by 851597064** [comment]
Rudi is there any progress or this or is there any way for us to assist? I could use QR codes in Obsidian on iOS for sure.

**Comment by rudimuc** [comment]
I will give it a try in December when I have little more time to investigate the possible reasons.

**Comment by 851597064** [comment]
That would be great. 

My usecase: I have a public function often working outdoors and many times I can assist people by sending them to some website. Using a dynamically generated QR code on my iOS phone is much easier and faster then spelling out a long difficult URL to them.

 

Thx

 

From: "Rudi Häusler - ***@***.***" ***@***.***>
Reply to: ***@***.***" ***@***.***>
Date: Thursday, 1 December 2022 at 13:38
To: rudimuc/obsidian-qrcode ***@***.***>
Cc: Paul S ***@***.***>, Comment ***@***.***>
Subject: Re: [rudimuc/obsidian-qrcode] Plugin fails to load on iOS (#2)
1597064: message 6 of 20)

 

I will give it a try in December when I have little more time to investigate the possible reasons.

**Comment by rudimuc** [comment]
@AnalogCyan @davidolrik @851597064 
I made some small changes and also updated the qrcode lib. I checked it out on iOS.... and it works :-)
So please update to 1.1.0 and you will enjoy it.

Thank you all for your patience - took quite long time to get that fixed.
Best regards from Munich!

**Comment by 851597064** [comment]
Very nice. Goodbye lots of QR code images files.
