### ISSUE TITLE
placement of the QR and Linkt/Text next to it

### ISSUE THREAD

**Issue by thebigalwisi** [rudimuc/obsidian-qrcode#3]
Hi rudimuc,

very nice app for obsidian. I like it!

Could you please add more options for the placement of the QR code (left, middle, right)? And what would be even more important (at least for me) would be the possibility to place a link/text next to it. I have put together an image here as a suggestion. Please don't pay attention to the wrong command wording (I don't know how to use it, it's just meant as a suggestion). 

![Screenshot from 2022-02-12 14-49-16](https://user-images.githubusercontent.com/85204944/153714528-db172e83-3983-45b8-8c6a-6dc2965deed3.png)
![Example1](https://user-images.githubusercontent.com/85204944/153714577-0e1ed518-1727-48e0-919d-4185cb7e3efe.png)

That would be great!  Thanks!

**Comment by rudimuc** [comment]
Hi thebigalwisi,
thanks for using my plugin and your feedback.
First of all it sounds like a reasonable enhancement. It took me some time thinking about your request so please apologize my late answer.
In my opinion adding texts and placements to the qr code statement would make things very complex. I'm thinking of all the parameters, like margins to the text, vertical/horizontal alignments, the width of the text block, text alignments to left or right etc. 
Wouldn't it be better to realize that with tables that wrap the qr code?

My strategy for this plugin is to concentrate on the qr code itself and keep the usage as simple as possible.
