### ISSUE TITLE
Installed, aktivated, but not in the plugin-list and not working

### ISSUE THREAD

**Issue by kwba** [rudimuc/obsidian-qrcode#4]
Hi,
helpful plugin. Unfortunately did not get it to work. Installed and activated via Obsidian. Plugin appears in the list of installed plugins, but not in the left list in the settings menu. Which is fine, because there are no settings for the plugin either. To test and use: I just copied the example (with the three dashes above). Then I looked at the result in the preview. Unfortunately, no QR code. What have I overlooked?
Thanks for a short feedback! 
Best regards with greetings to Munich
kwba

**Comment by rudimuc** [comment]
Hi!
Thanks for giving the plugin a try!
I have some questions to understand the problem better.
Which OS are you using?
Is the plugin in the plugin list activated?
Which signs are the three quotation marks exactly? It should be ```
Best regards
Rudi

**Comment by kwba** [comment]
Hi,
thanks for your answer! Now, it is working. What I did? I do not really know. I was retrying again and again. I suppose, "real" copy and paste of your examples from this website is not working. The better idea: typing letter by letter with the keyboard!
Anyway. I am very happy, that it is working now. Thanks for your input and thanks for your work. Very helpful. Markdown at its best!
Best regards,
kwba

**Comment by rudimuc** [comment]
Hi kwba,
yeah, you are right. There was an issue and it lead to a not well formatted string on my github page. 
I'm really sorry for this and that it took you much time to find the reason.
I just fixed it - copying the code sample works now.
Have fun and thanks for your input
Rudi
